"""Phase 0 (2.3/2.11): user auth hardening columns

Revision ID: 205f2ccb31f4
Revises: 4256b7f57a0d
Create Date: 2026-09-28 22:41:20.542881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205f2ccb31f4'
down_revision = '4256b7f57a0d'
branch_labels = None
depends_on = None


def upgrade():
    # NOT NULL columns need a server_default when added to a table that
    # already has rows -- SQLite (and Postgres) both reject an ADD COLUMN
    # NOT NULL with no default against existing data. The defaults are
    # dropped again below once every existing row has a concrete value, so
    # the schema doesn't carry a stale default that diverges from the
    # model (which relies on the Python-side `default=` instead).
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_version', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('password_reset_token_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('password_reset_expires_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('token_version', server_default=None)
        batch_op.alter_column('must_change_password', server_default=None)
        batch_op.alter_column('failed_login_attempts', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_reset_expires_at')
        batch_op.drop_column('password_reset_token_hash')
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_attempts')
        batch_op.drop_column('must_change_password')
        batch_op.drop_column('token_version')

    # ### end Alembic commands ###
