"""Phase 5: audit management (audits, findings, finding_control_links, assessments.audit_id)

Revision ID: 4256b7f57a0d
Revises: d33b80845fde
Create Date: 2026-07-05 21:56:05.367011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4256b7f57a0d'
down_revision = 'd33b80845fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('scope_description', sa.Text(), nullable=True),
    sa.Column('lead_auditor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_auditor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audits_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audits_lead_auditor_id'), ['lead_auditor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audits_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audits_status'), ['status'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('management_response', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_status'), ['status'], unique=False)

    op.create_table('finding_control_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('control_result_id', sa.Integer(), nullable=False),
    sa.Column('linked_by_id', sa.Integer(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['control_result_id'], ['control_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['linked_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id', 'control_result_id', name='uq_finding_control')
    )
    with op.batch_alter_table('finding_control_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_control_links_control_result_id'), ['control_result_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_control_links_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_control_links_org_id'), ['org_id'], unique=False)

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audit_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_assessments_audit_id'), ['audit_id'], unique=False)
        batch_op.create_foreign_key('fk_assessments_audit_id_audits', 'audits', ['audit_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assessments_audit_id_audits', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_assessments_audit_id'))
        batch_op.drop_column('audit_id')

    with op.batch_alter_table('finding_control_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_control_links_org_id'))
        batch_op.drop_index(batch_op.f('ix_finding_control_links_finding_id'))
        batch_op.drop_index(batch_op.f('ix_finding_control_links_control_result_id'))

    op.drop_table('finding_control_links')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_status'))
        batch_op.drop_index(batch_op.f('ix_findings_severity'))
        batch_op.drop_index(batch_op.f('ix_findings_owner_id'))
        batch_op.drop_index(batch_op.f('ix_findings_org_id'))
        batch_op.drop_index(batch_op.f('ix_findings_created_at'))
        batch_op.drop_index(batch_op.f('ix_findings_audit_id'))

    op.drop_table('findings')
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audits_status'))
        batch_op.drop_index(batch_op.f('ix_audits_org_id'))
        batch_op.drop_index(batch_op.f('ix_audits_lead_auditor_id'))
        batch_op.drop_index(batch_op.f('ix_audits_created_at'))

    op.drop_table('audits')
    # ### end Alembic commands ###
