"""Phase 0 (2.6): audit log and soft deletes

Revision ID: 650bcc795b6e
Revises: 205f2ccb31f4
Create Date: 2026-09-28 22:51:08.720721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650bcc795b6e'
down_revision = '205f2ccb31f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_ip', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_org_id'), ['org_id'], unique=False)

    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_audits_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_foreign_key('fk_audits_deleted_by_id_users', 'users', ['deleted_by_id'], ['id'])

    with op.batch_alter_table('evidence_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_evidence_files_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_foreign_key('fk_evidence_files_deleted_by_id_users', 'users', ['deleted_by_id'], ['id'])

    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_findings_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_foreign_key('fk_findings_deleted_by_id_users', 'users', ['deleted_by_id'], ['id'])

    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_risks_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_foreign_key('fk_risks_deleted_by_id_users', 'users', ['deleted_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_risks_deleted_by_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_risks_deleted_at'))
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_findings_deleted_by_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_findings_deleted_at'))
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('evidence_files', schema=None) as batch_op:
        batch_op.drop_constraint('fk_evidence_files_deleted_by_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_evidence_files_deleted_at'))
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.drop_constraint('fk_audits_deleted_by_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_audits_deleted_at'))
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_org_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
