"""Phase 6-8: vendors, contracts, policy watches, maturity, audit trail, token revocation

Autogenerated by `flask db migrate`, then hand-corrected in three places:
named FK constraints (alembic renders drop_constraint(None) for unnamed SQLite
FKs, which fails on downgrade), and server_default on every NOT NULL column
added to a populated table (assessments.source, assessments.
framework_definition_drift, users.token_version, users.must_change_password) —
without a backfill value the table rebuild errors on any non-empty database.

Revision ID: 7260ed955c59
Revises: 4256b7f57a0d
Create Date: 2026-09-28 17:12:54.059387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7260ed955c59'
down_revision = '4256b7f57a0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_rate_limit_buckets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bucket_key', sa.String(length=200), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('window_started_at', sa.DateTime(), nullable=False),
    sa.Column('window_expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_rate_limit_buckets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_rate_limit_buckets_bucket_key'), ['bucket_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_rate_limit_buckets_window_expires_at'), ['window_expires_at'], unique=False)

    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('service_description', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('data_sensitivity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('contract_start', sa.Date(), nullable=True),
    sa.Column('contract_end', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('review_frequency_days', sa.Integer(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('latest_overall_score', sa.Float(), nullable=True),
    sa.Column('risk_tier', sa.String(length=20), nullable=False),
    sa.Column('open_gap_count', sa.Integer(), nullable=False),
    sa.Column('last_assessment_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendors_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendors_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendors_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendors_risk_tier'), ['risk_tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendors_status'), ['status'], unique=False)

    op.create_table('vendor_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('contract_type', sa.String(length=40), nullable=False),
    sa.Column('frameworks', sa.JSON(), nullable=True),
    sa.Column('signed_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('auto_renews', sa.Boolean(), nullable=False),
    sa.Column('breach_notification_hours', sa.Integer(), nullable=True),
    sa.Column('audit_rights', sa.Boolean(), nullable=True),
    sa.Column('sub_processors_permitted', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_contracts_expires_on'), ['expires_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_contracts_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_contracts_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('audit_trail_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=60), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_trail_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_trail_entity', ['entity_type', 'entity_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_trail_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_trail_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_trail_events_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_trail_events_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_trail_events_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_trail_events_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_trail_events_user_id'), ['user_id'], unique=False)

    op.create_table('maturity_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('target_level', sa.Integer(), nullable=False),
    sa.Column('derived_level', sa.Integer(), nullable=False),
    sa.Column('derived_score', sa.Float(), nullable=False),
    sa.Column('level_rationale', sa.JSON(), nullable=True),
    sa.Column('capped_by_evidence', sa.Boolean(), nullable=False),
    sa.Column('self_assessment_notes', sa.Text(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('review_due_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'framework', name='uq_maturity_org_framework')
    )
    with op.batch_alter_table('maturity_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maturity_assessments_org_id'), ['org_id'], unique=False)

    op.create_table('policy_watches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('review_interval_days', sa.Integer(), nullable=False),
    sa.Column('drift_threshold_points', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_due_at', sa.DateTime(), nullable=True),
    sa.Column('last_score', sa.Float(), nullable=True),
    sa.Column('previous_score', sa.Float(), nullable=True),
    sa.Column('last_state', sa.String(length=20), nullable=True),
    sa.Column('consecutive_overdue_runs', sa.Integer(), nullable=False),
    sa.Column('last_assessment_id', sa.Integer(), nullable=True),
    sa.Column('last_content_hash', sa.String(length=64), nullable=True),
    sa.Column('last_framework_hash', sa.String(length=64), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_watches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_watches_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_watches_next_due_at'), ['next_due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_watches_org_id'), ['org_id'], unique=False)

    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revoked_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_revoked_tokens_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_revoked_tokens_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revoked_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('maturity_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('maturity_id', sa.Integer(), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['maturity_id'], ['maturity_assessments.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maturity_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maturity_snapshots_maturity_id'), ['maturity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maturity_snapshots_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maturity_snapshots_taken_at'), ['taken_at'], unique=False)

    op.create_table('policy_watch_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('watch_id', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('baseline_assessment_id', sa.Integer(), nullable=True),
    sa.Column('current_assessment_id', sa.Integer(), nullable=True),
    sa.Column('previous_score', sa.Float(), nullable=True),
    sa.Column('current_score', sa.Float(), nullable=True),
    sa.Column('score_delta', sa.Float(), nullable=True),
    sa.Column('controls_flipped', sa.JSON(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['baseline_assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['current_assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['watch_id'], ['policy_watches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_watch_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_watch_runs_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_watch_runs_run_at'), ['run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_watch_runs_watch_id'), ['watch_id'], unique=False)

    op.create_table('finding_vendor_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('linked_by_id', sa.Integer(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id', 'vendor_id', name='uq_finding_vendor')
    )
    with op.batch_alter_table('finding_vendor_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_vendor_links_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_vendor_links_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_vendor_links_vendor_id'), ['vendor_id'], unique=False)

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=True))
        # server_default backfills existing rows: every assessment recorded before
        # Phase 7 was produced by a human upload, so 'manual' is the truthful
        # value for history rather than a placeholder.
        batch_op.add_column(sa.Column('source', sa.String(length=20), nullable=False,
                                      server_default='manual'))
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('framework_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('parent_assessment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('framework_definition_drift', sa.Boolean(), nullable=False,
                                      server_default=sa.false()))
        batch_op.create_index(batch_op.f('ix_assessments_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_parent_assessment_id'), ['parent_assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_vendor_id'), ['vendor_id'], unique=False)
        batch_op.create_foreign_key('fk_assessments_parent_assessment_id', 'assessments',
                                    ['parent_assessment_id'], ['id'])
        batch_op.create_foreign_key('fk_assessments_vendor_id', 'vendors', ['vendor_id'], ['id'])

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_policy_review_interval_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('default_vendor_review_interval_days', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('token_version', sa.Integer(), nullable=False,
                                      server_default='0'))
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False,
                                      server_default=sa.false()))
        batch_op.add_column(sa.Column('password_changed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_changed_at')
        batch_op.drop_column('must_change_password')
        batch_op.drop_column('token_version')
        batch_op.drop_column('last_login_at')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('default_vendor_review_interval_days')
        batch_op.drop_column('default_policy_review_interval_days')

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assessments_vendor_id', type_='foreignkey')
        batch_op.drop_constraint('fk_assessments_parent_assessment_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_assessments_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_assessments_parent_assessment_id'))
        batch_op.drop_index(batch_op.f('ix_assessments_content_hash'))
        batch_op.drop_column('framework_definition_drift')
        batch_op.drop_column('parent_assessment_id')
        batch_op.drop_column('framework_hash')
        batch_op.drop_column('content_hash')
        batch_op.drop_column('source')
        batch_op.drop_column('vendor_id')

    with op.batch_alter_table('finding_vendor_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_vendor_links_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_finding_vendor_links_org_id'))
        batch_op.drop_index(batch_op.f('ix_finding_vendor_links_finding_id'))

    op.drop_table('finding_vendor_links')
    with op.batch_alter_table('policy_watch_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_watch_runs_watch_id'))
        batch_op.drop_index(batch_op.f('ix_policy_watch_runs_run_at'))
        batch_op.drop_index(batch_op.f('ix_policy_watch_runs_org_id'))

    op.drop_table('policy_watch_runs')
    with op.batch_alter_table('maturity_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maturity_snapshots_taken_at'))
        batch_op.drop_index(batch_op.f('ix_maturity_snapshots_org_id'))
        batch_op.drop_index(batch_op.f('ix_maturity_snapshots_maturity_id'))

    op.drop_table('maturity_snapshots')
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_org_id'))
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_jti'))
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_expires_at'))

    op.drop_table('revoked_tokens')
    with op.batch_alter_table('policy_watches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_watches_org_id'))
        batch_op.drop_index(batch_op.f('ix_policy_watches_next_due_at'))
        batch_op.drop_index(batch_op.f('ix_policy_watches_is_active'))

    op.drop_table('policy_watches')
    with op.batch_alter_table('maturity_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maturity_assessments_org_id'))

    op.drop_table('maturity_assessments')
    with op.batch_alter_table('audit_trail_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_trail_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_trail_events_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_trail_events_org_id'))
        batch_op.drop_index(batch_op.f('ix_audit_trail_events_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_trail_events_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_trail_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_trail_events_action'))
        batch_op.drop_index('ix_audit_trail_entity')

    op.drop_table('audit_trail_events')
    with op.batch_alter_table('vendor_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_contracts_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_contracts_org_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_contracts_expires_on'))

    op.drop_table('vendor_contracts')
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_status'))
        batch_op.drop_index(batch_op.f('ix_vendors_risk_tier'))
        batch_op.drop_index(batch_op.f('ix_vendors_owner_id'))
        batch_op.drop_index(batch_op.f('ix_vendors_org_id'))
        batch_op.drop_index(batch_op.f('ix_vendors_created_at'))

    op.drop_table('vendors')
    with op.batch_alter_table('api_rate_limit_buckets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_rate_limit_buckets_window_expires_at'))
        batch_op.drop_index(batch_op.f('ix_api_rate_limit_buckets_bucket_key'))

    op.drop_table('api_rate_limit_buckets')
    # ### end Alembic commands ###
