"""Phase 4: risk register (risks, risk_control_links)

Revision ID: d33b80845fde
Revises: eaa8ce4b9b93
Create Date: 2026-07-05 16:57:28.283831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33b80845fde'
down_revision = 'eaa8ce4b9b93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('likelihood', sa.Integer(), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mitigation', sa.Text(), nullable=True),
    sa.Column('residual_likelihood', sa.Integer(), nullable=True),
    sa.Column('residual_impact', sa.Integer(), nullable=True),
    sa.Column('residual_risk_score', sa.Integer(), nullable=True),
    sa.Column('residual_risk_level', sa.String(length=20), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_risks_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risks_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risks_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_risks_status'), ['status'], unique=False)

    op.create_table('risk_control_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.Column('control_result_id', sa.Integer(), nullable=False),
    sa.Column('linked_by_id', sa.Integer(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['control_result_id'], ['control_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('risk_id', 'control_result_id', name='uq_risk_control')
    )
    with op.batch_alter_table('risk_control_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_control_links_control_result_id'), ['control_result_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_control_links_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_control_links_risk_id'), ['risk_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_control_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_control_links_risk_id'))
        batch_op.drop_index(batch_op.f('ix_risk_control_links_org_id'))
        batch_op.drop_index(batch_op.f('ix_risk_control_links_control_result_id'))

    op.drop_table('risk_control_links')
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risks_status'))
        batch_op.drop_index(batch_op.f('ix_risks_risk_level'))
        batch_op.drop_index(batch_op.f('ix_risks_owner_id'))
        batch_op.drop_index(batch_op.f('ix_risks_org_id'))
        batch_op.drop_index(batch_op.f('ix_risks_created_at'))

    op.drop_table('risks')
    # ### end Alembic commands ###
