"""Phase 2: reviewer/remediation fields, evidence_files table

Revision ID: eaa8ce4b9b93
Revises: 9165998c81f9
Create Date: 2026-07-03 19:42:33.310563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaa8ce4b9b93'
down_revision = '9165998c81f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('control_result_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('stored_filename', sa.String(length=600), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['control_result_id'], ['control_results.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_files_control_result_id'), ['control_result_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_files_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_files_uploaded_at'), ['uploaded_at'], unique=False)

    with op.batch_alter_table('control_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('reviewer_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('reviewer_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('assigned_to_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('remediation_status', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_control_results_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_control_results_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_control_results_remediation_status'), ['remediation_status'], unique=False)
        batch_op.create_foreign_key('fk_control_results_org_id_organizations', 'organizations', ['org_id'], ['id'])
        batch_op.create_foreign_key('fk_control_results_assigned_to_id_users', 'users', ['assigned_to_id'], ['id'])
        batch_op.create_foreign_key('fk_control_results_reviewed_by_id_users', 'users', ['reviewed_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('control_results', schema=None) as batch_op:
        batch_op.drop_constraint('fk_control_results_reviewed_by_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_control_results_assigned_to_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_control_results_org_id_organizations', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_control_results_remediation_status'))
        batch_op.drop_index(batch_op.f('ix_control_results_org_id'))
        batch_op.drop_index(batch_op.f('ix_control_results_assigned_to_id'))
        batch_op.drop_column('remediation_status')
        batch_op.drop_column('due_date')
        batch_op.drop_column('assigned_to_id')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by_id')
        batch_op.drop_column('reviewer_note')
        batch_op.drop_column('reviewer_status')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('evidence_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_files_uploaded_at'))
        batch_op.drop_index(batch_op.f('ix_evidence_files_org_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_files_control_result_id'))

    op.drop_table('evidence_files')
    # ### end Alembic commands ###
