"""Phase 0 (2.7): segregation-of-duties pending-request fields

Revision ID: ecd220602e78
Revises: 650bcc795b6e
Create Date: 2026-09-28 22:55:28.419117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd220602e78'
down_revision = '650bcc795b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_action', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('pending_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pending_requested_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pending_requested_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(
            'fk_findings_pending_requested_by_id_users', 'users', ['pending_requested_by_id'], ['id']
        )

    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_acceptance_expires_at', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('pending_action', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('pending_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pending_expiry_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('pending_requested_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pending_requested_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(
            'fk_risks_pending_requested_by_id_users', 'users', ['pending_requested_by_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_risks_pending_requested_by_id_users', type_='foreignkey')
        batch_op.drop_column('pending_requested_at')
        batch_op.drop_column('pending_requested_by_id')
        batch_op.drop_column('pending_expiry_date')
        batch_op.drop_column('pending_reason')
        batch_op.drop_column('pending_action')
        batch_op.drop_column('risk_acceptance_expires_at')

    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_findings_pending_requested_by_id_users', type_='foreignkey')
        batch_op.drop_column('pending_requested_at')
        batch_op.drop_column('pending_requested_by_id')
        batch_op.drop_column('pending_reason')
        batch_op.drop_column('pending_action')

    # ### end Alembic commands ###
